### PR TITLE
RNs 36448, 36449, 36450, 36451, and 36452

### PR DESCRIPTION
**Pull request by MariekeGO**

### CODE REVIEW

**Comment by MariekeGO** [comment]
I've now also added [RN 36459](https://github.com/SkylineCommunications/dataminer-docs/pull/1495/commits/cceae0d8102b550f768c1b2947fcfc34b75e0929). @MariaCUSkyline, could you take a look at this?

**Review by MariaCUSkyline — APPROVED** [review]

**Comment by MariekeGO** [comment]
@miguel-slc, could you confirm if this is OK to merge?

**Review by miguel-slc — COMMENTED** [review]
_Overview pages have been added for the passive levels (node, amplifier, and tap), which display the KPIs for the selected entry and contain links to navigate to a dashboard with all cable modems associated with the selected device._

Could we indicate list which KPIs are displayed in the overview pages?

_Inter-app calls are now aggregated to send information to the back end._
Please could we enhance this comment an indicate that we are referring to the backend elements.

_Information from the back end is now processed through inter-app communication._
Information coming from backend elements are now processed through interapp communication

_Geomarketing DB passive tables no longer displayed + new export button [ID_36449]_
GeoMarketing is only used for one specific customer. To double check if it should be included as part of the standard solution

_ID columns hidden on topology data pages [ID_36451]_
For the sake of transparency, please could we list which parameters where hidden

_Exception values added for percentage, latitude, and longitude parameters [ID_36452]_
Please could we indicate what displayed value is used when an exception occurs (is it 'N/A', 'NA', 'Not Applicable')?

_The filters of the XML that controls the maps have been adjusted to correct this issue._
Please indicate which specific XML file we are referring to. If I am not mistaken is the map config file

**Review by MarcosMMA — CHANGES_REQUESTED** [review]

**Comment by MariekeGO** [comment]
> _Overview pages have been added for the passive levels (node, amplifier, and tap), which display the KPIs for the selected entry and contain links to navigate to a dashboard with all cable modems associated with the selected device._
> 
> Could we indicate list which KPIs are displayed in the overview pages?
> 
> _Inter-app calls are now aggregated to send information to the back end._ Please could we enhance this comment an indicate that we are referring to the backend elements.
> 
> _Information from the back end is now processed through inter-app communication._ Information coming from backend elements are now processed through interapp communication
> 
> _Geomarketing DB passive tables no longer displayed + new export button [ID_36449]_ GeoMarketing is only used for one specific customer. To double check if it should be included as part of the standard solution
> 
> _ID columns hidden on topology data pages [ID_36451]_ For the sake of transparency, please could we list which parameters where hidden
> 
> _Exception values added for percentage, latitude, and longitude parameters [ID_36452]_ Please could we indicate what displayed value is used when an exception occurs (is it 'N/A', 'NA', 'Not Applicable')?
> 
> _The filters of the XML that controls the maps have been adjusted to correct this issue._ Please indicate which specific XML file we are referring to. If I am not mistaken is the map config file

All these issues have been addressed. Could you confirm if this is now OK to merge?

**Comment by miguel-slc** [comment]
it is ok to merge.

**Review by MarcosMMA — COMMENTED** [review]
Seems good to me. Thanks!

**Pull request merged**
