### PR TITLE
I-DOCSIS 6.1.9 CU1 update - RN 38287

### PR DESCRIPTION
**Pull request by MariekeGO**

### CODE REVIEW

**Review by miguel-slc — COMMENTED** [review]
Please could we include from where these KPIs are being retrieved?
From the CCAP, or the collector?

**Comment by MariekeGO** [comment]
> Please could we include from where these KPIs are being retrieved? From the CCAP, or the collector?

@EstebanSkyline, could you provide this information?

**Comment by EstebanSkyline** [comment]
> > Please could we include from where these KPIs are being retrieved? From the CCAP, or the collector?
> 
> @EstebanSkyline, could you provide this information?

Hello, sure ! 
The information is being retrieved from the CCAP

**Review by miguel-slc — APPROVED** [review]
It looks ok

**Pull request merged**
