### PR TITLE
Update Granting_admin_consent.md

### PR DESCRIPTION
**Pull request by JordyGit**

### CODE REVIEW

**Comment by JordyGit** [comment]
Line 26: "grant consent for the required permissions"
Maybe add a note the permissions can vary with the provided GIF 
Maybe add a note the required permissions can change when new features are released

**Comment by JordyGit** [comment]
Maybe the image on bullet point 2 could use some trimming :) https://docs.dataminer.services/user-guide/Cloud_Platform/CloudAdminApp/Granting_admin_consent.html

**Comment by MariekeGO** [comment]
@JordyGit I've added several changes based on your feedback. Let me know what you think!

**Review by JordyGit — COMMENTED** [review]
Looks good!

**Review by MariekeGO — APPROVED** [review]

**Pull request merged**
