### PR TITLE
Catalog API in user guide

### PR DESCRIPTION
**Pull request by MariekeGO**
@baptistepa & @SkylineKevinMOR, could you take a look at this PR to add the Catalog API to the user guide? This is a first draft, so changes or more extensive info may be needed.

### CODE REVIEW

**Review by SkylineKevinMOR — APPROVED** [review]
Looks good to me

**Comment by baptistepa** [comment]
I do not think it is a good idea to document this... This will be yet another place where we need to document the API. ATm we have docs auto generated at https://catalogapi-prod.cca-prod.aks.westeurope.dataminer.services/swagger/index.html?urls.primaryName=User%20Catalog%20API%20v1.0. We could move this to a better URL if we want in the future.

**Comment by baptistepa** [comment]
@AlexanderVK-SLC what do you think?

**Comment by AlexanderVK-SLC** [comment]
The URL can be accessed by everyone, yes, and the swagger is the closest source of truth. However, I would prefer to move it behind api.dataminer.services/.../swagger url before adding it to the docs, because these URLs will not change unlike the direct cluster URL.

It's also a good motivator for us to keep our swagger well documented, knowing that it is consumed by external users directly without UI.

**Comment by MariekeGO** [comment]
> The URL can be accessed by everyone, yes, and the swagger is the closest source of truth. However, I would prefer to move it behind api.dataminer.services/.../swagger url before adding it to the docs, because these URLs will not change unlike the direct cluster URL.
> 
> It's also a good motivator for us to keep our swagger well documented, knowing that it is consumed by external users directly without UI.

In that case, I'd simply close the current PR for now. Could you create a PR to add the link once it's available?

**Pull request closed without merging**
