### PR TITLE
Update SRM_1.2.36.md

### PR DESCRIPTION
**Pull request by JensVandewalle**
Since it's compatible with FR 10.3.2 it is compatible with MR 10.4.0

### CODE REVIEW

**Comment by MariekeGO** [comment]
@peter-vanpoucke, is this change OK? I thought this version of SRM was only suitable for use with the feature release, but possibly it is indeed OK with the main release from 10.4 onwards?

**Comment by slc-peter-vanpoucke** [comment]
Strictly speaking that's right. The minimum version can change between feature release track versions though, which we'll try to avoid for the main release track. So it's better to pick that one for DM main releases, to avoid surprises.

I'll check with the team if we keep it that way.

**Review by slc-peter-vanpoucke — CHANGES_REQUESTED** [review]
Might be worth rephrasing indeed. The same note should also be on SRM_2.0.1.

**Comment by MariekeGO** [comment]
> Might be worth rephrasing indeed. The same note should also be on SRM_2.0.1.

I've rephrased the note where relevant and added it for 2.0.1 as well. Does this look OK for you?

**Review by slc-peter-vanpoucke — APPROVED** [review]

**Review by MariekeGO — APPROVED** [review]

**Pull request merged**
