### PR TITLE
EPM 6.1.9 CU1 update

### PR DESCRIPTION
**Pull request by MariekeGO**
The page https://docs.dataminer.services/user-guide/Standard_Apps/EPM/EPM_I-DOCSIS/I-DOCSIS_Create_CCAP_CM_pair.html will also need to be updated with these changes. @EstebanSkyline, could you create a pull request for this?  
Also, note that on that page only the get community string is mentioned, while in the release note it says that up to now only the set community string was supported. Is this a mistake in the release note?

### CODE REVIEW

**Comment by MariekeGO** [comment]
Changes to the user guide for RN 38326 were done with #2567.

**Comment by MariekeGO** [comment]
@miguel-slc 
Additional missing release notes have been added. Note that [36751](https://intranet.skyline.be/DataMiner/Lists/Release%20Notes/DispForm.aspx?ID=36751) mentioned that #CM Ping OK has been changed to #CM Ping Unreachable, which seems a bit odd. Could you check this? Also, if this is indeed OK, it will also need to be updated in the user guide.

**Comment by miguel-slc** [comment]
Hi @MariekeGO, I checked internally and the comment available in RN is not clear enough. It should be as follows:
- The parameter #CM Ping Unreachable is now displayed
- The parameter #CM Ping OK is now hidden (since it does not provide meaningful information)
@EstebanSkyline, can you help me updating the user guide?

**Comment by EstebanSkyline** [comment]
> Hi @MariekeGO, I checked internally and the comment available in RN is not clear enough. It should be as follows:
> 
> * The parameter #CM Ping Unreachable is now displayed
> * The parameter #CM Ping OK is now hidden (since it does not provide meaningful information)
>   @EstebanSkyline, can you help me updating the user guide?

Hello, @miguel-slc 

Are you referring to the user guide for the new CCAP/CM pair script? Or are you addressing the general guide regarding the #CM Ping issue?

If your concern pertains to the CCAP script, I recently addressed some remarks provided by @MariekeGO a while back, although I seem to have forgotten about them.

**Comment by miguel-slc** [comment]
Hi @EstebanSkyline, addressing the general guide regarding the #CM Ping issue?

**Comment by miguel-slc** [comment]
It looks ok

**Review by miguel-slc — APPROVED** [review]

**Pull request merged**
