### PR TITLE
Update ST_Determining_characteristics_generated_service.md

### PR DESCRIPTION
**Pull request by jimmyveloz**
Path to upload the Visio file

### CODE REVIEW

**Review by MariekeGO — COMMENTED** [review]
I've made some changes to your pull request to make sure the note reads better. Could you take a look? Also, could you confirm that your addition only applies for VDX files, and not for ZIP or VSDX files? This seems a little odd.

**Review by HansSolos — CHANGES_REQUESTED** [review]
VDX and ZIP are legacy for Visio files. I would only test for VSDX files and mentioned that.
More info: The VDX format is not supported in Visio 2013 and later.

**Comment by jimmyveloz** [comment]
Hi Marieke, aside of what Matthias mentioned I think the first mention of VDX file could be a typo? first is referring to VDX file and then to VSDX. I think for that reason looks odd.

**Comment by MariekeGO** [comment]
> Hi Marieke, aside of what Matthias mentioned I think the first mention of VDX file could be a typo? first is referring to VDX file and then to VSDX. I think for that reason looks odd.

I've adjusted the note. Could you check if everything looks OK?

**Review by HansSolos — APPROVED** [review]

**Comment by jimmyveloz** [comment]
Hi, it looks good for me, thanks

**Review by MariekeGO — APPROVED** [review]

**Pull request merged**
