### PR TITLE
List view update

### PR DESCRIPTION
**Pull request by MariekeGO**

### CODE REVIEW

**Review by karlmasschelein — CHANGES_REQUESTED** [review]
Added changes look fine to me.
As the columntype 'Custom icon' seems to got broken and is not currently used by customers, I created task [Cube listview column support for custom icons broken](https://collaboration.dataminer.services/task/198216) to restore this functionality. Maybe we should omit this information temporarily.

**Comment by MariekeGO** [comment]
> Added changes look fine to me. As the columntype 'Custom icon' seems to got broken and is not currently used by customers, I created task [Cube listview column support for custom icons broken](https://collaboration.dataminer.services/task/198216) to restore this functionality. Maybe we should omit this information temporarily.

Since it's available in the UI, I'll keep the option in the documentation, but I'll mention that it shouldn't be used at the moment.

**Review by karlmasschelein — COMMENTED** [review]
Seems odd ? 'This column type can currently not be used.'
This column type can't currently be used.

**Comment by MariekeGO** [comment]
> Seems odd ? 'This column type can currently not be used.' This column type can't currently be used.

I'll adjust this. However, note that contractions (e.g. can't) should not be used in the documentation. See [https://docs.dataminer.services/CONTRIBUTING.html#avoid-contractions](https://docs.dataminer.services/CONTRIBUTING.html#avoid-contractions).

**Pull request merged**
