### PR TITLE
Update DataMiner_Extension_Modules.md

### PR DESCRIPTION
**Pull request by lustpieter**
Updated information of CloudFeed.

### CODE REVIEW

**Comment by MariekeGO** [comment]
@lustpieter, I've reviewed your PR and made some changes. Could you check if everything is still OK for you?

**Comment by lustpieter** [comment]
All is Okay for me. Hold off with submitting. The code commit accompanying this documentation change hasn't been merged yet.

**Comment by MariekeGO** [comment]
> Code has been merged into RC. 10.4.10 hasn't been released yet. Let alone sealed. not sure if this can be submitted then?

Is there a release note for this change? Usually, we can add information in advance when the corresponding release note is set to be released in a specific version, as long as we make sure the version info is clear in the documentation.

**Comment by lustpieter** [comment]
Yes, then it's fine. [RN40413](https://intranet.skyline.be/DataMiner/Lists/Release%20Notes/DispForm2.aspx?ID=40413).
Then this can be submitted.

**Pull request merged**
