### PR TITLE
Update DB_xml.md

### PR DESCRIPTION
**Pull request by robin-devos-skyline**
Based on DCP64018/RN15345
@Tom-Van-Bruaene and @bertbsky could you verify this addition? I found your names in the DCP+RN

### CODE REVIEW

**Comment by MariekeGO** [comment]
@robin-devos-skyline, after a quick search, I found that this was not added to the documentation because it's possible to do this in Cube instead with the "Only keep the latest parameter value in the database (clear previous values)" option. 
image

As we prefer it if people don't mess around with XML files if there's a better alternative available directly in Cube, it seemed better to leave this out. Should this be added after all? Does adding the option in DB.xml actually do something different than this option?

**Comment by robin-devos-skyline** [comment]
@MariekeGO, I understand this perspective. 
The problem with this is, from my side, I only knew the clean option in the xml and I found nothing in the DM Docs, so I knew nothing. Even knowing that option in Cube, ie "Only keep the latest parame...", I had a hard time finding it in the DM Docs (I searched for "clear previous values" which seemed like more relevant terms). 
--> perhaps change "clear previous values" to "clea**N** previous values"? small change, but in a way it refers to the clean option, which does make a difference when searching.

Either way, final decision isn't for me to make. I know other xml tags/options/arguments aren't mentioned in the DM Docs either.

**Comment by robin-devos-skyline** [comment]
> > @MariekeGO, I understand this perspective. The problem with this is, from my side, I only knew the clean option in the xml and I found nothing in the DM Docs, so I knew nothing. Even knowing that option in Cube, ie "Only keep the latest parame...", I had a hard time finding it in the DM Docs (I searched for "clear previous values" which seemed like more relevant terms). --> perhaps change "clear previous values" to "clea**N** previous values"? small change, but in a way it refers to the clean option, which does make a difference when searching.
> > Either way, final decision isn't for me to make. I know other xml tags/options/arguments aren't mentioned in the DM Docs either.
> 
> Perhaps we can add a note mentioning that this option in Cube corresponds with the clean="true" configuration in the Offload tag in DB.xml? That way it will show up if you search for that configuration.

Sounds like a good idea 👍

**Comment by MariekeGO** [comment]
@robin-devos-skyline I've adjusted the PR based on the comments above. Could you take a look and let me know if this is OK for you?

**Review by robin-devos-skyline — COMMENTED** [review]
Approved :)

**Review by MariekeGO — APPROVED** [review]

**Pull request merged**
