### PR TITLE
RNs 36684 + 36686

### PR DESCRIPTION
**Pull request by MariekeGO**

### CODE REVIEW

**Review by SkylineGBO — COMMENTED** [review]
For RN 36684, the CM Channels were not touched, that should be handled in another RN, so dashboards *CM/02. CM DS QAM Channels*, *CM/03. CM US QAM Channels* can be removed.

For RN 36686, the Dashboard that was added was CM/01. CM Overview as well.

**Comment by MariekeGO** [comment]
> For RN 36684, the CM Channels were not touched, that should be handled in another RN, so dashboards _CM/02. CM DS QAM Channels_, _CM/03. CM US QAM Channels_ can be removed.
> 
> For RN 36686, the Dashboard that was added was CM/01. CM Overview as well.

I've updated the description for 36684, but your comment for 36686 isn't entirely clear to me. Do you mean it's only CM/01. CM Overview that was added there?

**Comment by SkylineGBO** [comment]
Yes, only the CM/01. CM Overview was added, the others were added in a previous RN.

In kind regards,

***@***.***<https://skyline.be/learn/events>


Gabriel Borges | Senior System Developer
Email ***@***.******@***.***>

Skyline Communications
1625 N Commerce Pkwy, Suite 207 | Weston, FL 33326 | USA
www.skyline.be<https://www.skyline.be/> | +1 (754) 218-2030<tel:+17542182030>

***@***.***<https://skyline.be/>


***@***.******@***.***>
***@***.***<https://community.dataminer.services/?utm_source=signature&utm_medium=email&utm_campaign=icon>
***@***.***<https://www.linkedin.com/company/skyline-communications>
***@***.***<https://www.youtube.com/user/SkylineCommu>
***@***.***<https://www.facebook.com/SkylineCommunications/>
***@***.***<https://www.instagram.com/skyline.dataminer/>
***@***.***<https://skyline.be/skyline/awards?utm_source=signature&utm_medium=email&utm_campaign=icon>

***@***.***

**Comment by miguel-slc** [comment]
it look ok

**Pull request merged**
