### PR TITLE
Prerequisite added

### PR DESCRIPTION
**Pull request by DanielMart97**
Added new prerequisite observed during a Cassandra Migration process

### CODE REVIEW

**Review by SkylineCookieMonster — CHANGES_REQUESTED** [review]
Hi Daniel,

Do you mean the system should not have had a restart in the last 24-48 hours prior to starting the DMAs or do you mean that DataMiner can't restart during the migration?

If it is the latter than I would not really see it as a prerequisite, but more as an important note?

**Comment by SkylineCookieMonster** [comment]
@DanielMart97 can you change it to:
"The DataMiner agents did not restart in the last 48hours"

**Comment by DanielMart97** [comment]
Done it!

**Review by SkylineCookieMonster — APPROVED** [review]

**Review by MariekeGO — APPROVED** [review]

**Comment by MariekeGO** [comment]
@DanielMart97, if you are in the DataMiner DevOps Professional Program, could you add your full name to your GitHub profile so we can assign your points for this PR? You can do so by clicking the icon in the top-right corner in GitHub, selecting “Your profile”, and then clicking “Edit Profile”.

**Comment by DanielMart97** [comment]
Full name added Marieke :)

**Comment by MariekeGO** [comment]
> Full name added Marieke :)

Thanks! The DevOps points will be added to your account soon :)

**Comment by DanielMart97** [comment]
> > Full name added Marieke :)
> 
> Thanks! The DevOps points will be added to your account soon :)

Thank you so much!

**Pull request merged**
