### PR TITLE
Children sort options for booking shapes

### PR DESCRIPTION
**Pull request by MariekeGO**

### CODE REVIEW

**Comment by MariekeGO** [comment]
@karlmasschelein, could you check if this is OK to merge?

**Comment by karlmasschelein** [comment]
Note : With [RN34864](https://intranet.skyline.be/DataMiner/Lists/Release Notes/DispForm.aspx?ID=34864) coming up, the ChildrenSort syntax will change to :
Property|property=Start,asc
We aim to release both RN34572 and RN34864 together on next feature release.

**Review by karlmasschelein — COMMENTED** [review]
Document changes seem fine for RN34572.

Note : With [RN34864](https://intranet.skyline.be/DataMiner/Lists/Release Notes/DispForm.aspx?ID=34864) coming up, the ChildrenSort syntax will change to :
Property|property=Start,asc
We aim to release both RN34572 and RN34864 together on next feature release.

**Comment by MariekeGO** [comment]
> Note : With RN 34864 coming up, the ChildrenSort syntax will change to : Property|property=Start,asc We aim to release both RN34572 and RN34864 together on next feature release.

Thanks for the heads-up; we'll add that once that release note has been merged.

**Pull request merged**
